# Generated by Django 5.2 on 2025-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_delete_almini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='dob',
            field=models.DateField(max_length=100),
        ),
    ]
