# Generated by Django 5.2 on 2025-05-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_alumni_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='classYear',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='otherContacts',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='phone',
        ),
        migrations.AddField(
            model_name='alumni',
            name='bio',
            field=models.TextField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='alumni',
            name='department',
            field=models.CharField(default='Department of Computer Science and Engineering', max_length=255),
        ),
        migrations.AddField(
            model_name='alumni',
            name='graduation_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(default='media/img.png', upload_to='alumni_photos/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='alumni',
            name='university',
            field=models.CharField(default='University of Asia Pacific', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
