# Generated by Django 5.2 on 2025-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_remove_alumni_classyear_remove_alumni_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='bio',
            field=models.TextField(default='null', max_length=3000),
        ),
    ]
