# Generated by Django 5.2 on 2025-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alter_alumni_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(default='alumni_photos/img.png', upload_to='alumni_photos/'),
        ),
    ]
