# Generated by Django 5.2 on 2025-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_name_alter_alumni_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(default='media/img.png', upload_to='alumni_photos/'),
        ),
    ]
