# Generated by Django 5.2 on 2025-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_alumni_name_alter_alumni_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='alumni_association/')),
            ],
        ),
    ]
